/usr/bin/Rscript ~/socialNetworkData/news-posts-with-R/DataCollection/FoxNews.R
/usr/bin/Rscript ~/socialNetworkData/news-posts-with-R/DataCollection/bbcnews.R
/usr/bin/Rscript ~/socialNetworkData/news-posts-with-R/DataCollection/cnbc.R
/usr/bin/Rscript ~/socialNetworkData/news-posts-with-R/DataCollection/dataLocation.R
/usr/bin/Rscript ~/socialNetworkData/news-posts-with-R/DataCollection/forbes.R
/usr/bin/Rscript ~/socialNetworkData/news-posts-with-R/DataCollection/latimes.R
/usr/bin/Rscript ~/socialNetworkData/news-posts-with-R/DataCollection/nytimes.R
/usr/bin/Rscript ~/socialNetworkData/news-posts-with-R/DataCollection/usatoday.R
/usr/bin/Rscript ~/socialNetworkData/news-posts-with-R/DataCollection/washingtonpost.R
/usr/bin/Rscript ~/socialNetworkData/news-posts-with-R/DataCollection/wsj.R
