/usr/bin/Rscript ~/socialNetworkData/news-posts-with-R/DataCollection/FoxNews.R
/usr/bin/Rscript bbcnews.R
/usr/bin/Rscript cnbc.R
/usr/bin/Rscript dataLocation.R
/usr/bin/Rscript forbes.R
/usr/bin/Rscript latimes.R
/usr/bin/Rscript nytimes.R
/usr/bin/Rscript usatoday.R
/usr/bin/Rscript washingtonpost.R
/usr/bin/Rscript wsj.R
